name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 2.1.1
homepage: https://github.com/Abdalqader27/introduction_screen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed: any
  build_runner: ^2.1.7
  flutter_bloc: ^8.0.1
  get_storage:
  dots_indicator: ^2.1.0
