name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.9
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # dots_indicator: ^1.2.0
  dots_indicator:
    git:
      url: https://github.com/hlavki/dots_indicator.git
      ref: master
